import os
import json
import time
import subprocess
import socket
from pathlib import Path
import typer
from rich.console import Console

from app.utils.pidfile import get_running_project_root
from devmemory_daemon.git_engine import devmemory_root

console = Console()
dashboard_app = typer.Typer(help="Run DevMemory web dashboard (FastAPI + Vue)")


def _find_free_port() -> int:
    """Find an available port"""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("", 0))
        return s.getsockname()[1]


def _create_env_config(dashboard_dir: Path, api_url: str):
    """Create env-config.js for Vue runtime configuration"""
    public_dir = dashboard_dir / "public"
    public_dir.mkdir(exist_ok=True, parents=True)

    config_content = f"""// Auto-generated by DevMemory CLI
window.DEVMEMORY_CONFIG = {{
  API_URL: "{api_url}"
}};
"""

    config_path = public_dir / "env-config.js"
    config_path.write_text(config_content)
    console.print(f"[dim]Runtime config created: {config_path}[/dim]")


def _detect_vue_port(start_port=5173, limit=10):
    """Detect Vite dev server port (default 5173)"""
    import http.client

    for p in range(start_port, start_port + limit):
        try:
            conn = http.client.HTTPConnection("127.0.0.1", p, timeout=0.3)
            conn.request("GET", "/")
            resp = conn.getresponse()
            html = resp.read().decode("utf-8", errors="ignore")

            if '<div id="app"' in html or "Vite" in html:
                return p
        except Exception:
            pass
    return None


def start_dashboard_background(project_root: Path):
    """
    Start API + Vite in the background for this project.
    Stores their PIDs in .devmemory/dashboard_pids.json.
    """
    CLI_ROOT = Path(__file__).resolve().parents[2]
    api_file = CLI_ROOT / "app" / "dashboard_api.py"
    dashboard_dir = CLI_ROOT / "dashboard"

    if not api_file.exists() or not dashboard_dir.exists():
        console.print(
            "[yellow]Dashboard not available; skipping dashboard startup.[/yellow]"
        )
        return None

    # Start API
    api_port = _find_free_port()
    api_url = f"http://127.0.0.1:{api_port}"
    _create_env_config(dashboard_dir, api_url)

    dm_root = devmemory_root(project_root)
    dm_root.mkdir(parents=True, exist_ok=True)
    api_log_path = dm_root / "dashboard-api.log"
    vite_log_path = dm_root / "dashboard-vite.log"

    try:
        api_proc = subprocess.Popen(
            [
                "uvicorn",
                "app.dashboard_api:app",
                "--host",
                "127.0.0.1",
                "--port",
                str(api_port),
            ],
            stdout=api_log_path.open("a"),
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )
    except FileNotFoundError:
        console.print("[yellow]uvicorn not found; dashboard API not started.[/yellow]")
        return None

    # Start Vite
    try:
        vite_proc = subprocess.Popen(
            ["npm", "run", "dev"],
            cwd=str(dashboard_dir),
            stdout=vite_log_path.open("a"),
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )
    except FileNotFoundError:
        console.print("[yellow]npm not found; frontend dashboard not started.[/yellow]")
        # We still keep the API
        vite_proc = None

    # Try to detect Vite port (default 5173)
    time.sleep(2)
    vue_port = _detect_vue_port(5173) or 5173

    # Save PIDs so `devmemory stop` can kill them
    pids_file = dm_root / "dashboard_pids.json"
    pids_file.write_text(
        json.dumps(
            {
                "api_pid": api_proc.pid,
                "vite_pid": vite_proc.pid if vite_proc else None,
                "api_port": api_port,
                "vue_port": vue_port,
            },
            indent=2,
        )
    )

    console.print(
        f"[dim]Dashboard API: http://127.0.0.1:{api_port} | UI: http://localhost:{vue_port}[/dim]"
    )

    return api_port, vue_port


@dashboard_app.command("run")
def dashboard_run():
    """Start FastAPI backend + Vue.js frontend"""

    # Check if DevMemory daemon is running
    project_root = get_running_project_root()
    if not project_root:
        console.print("[red]DevMemory daemon is not running.[/red]")
        console.print("Start it with: [bold]devmemory start[/bold]")
        raise typer.Exit(1)

    # Find directories
    CLI_ROOT = Path(__file__).resolve().parents[2]
    api_file = CLI_ROOT / "app" / "dashboard_api.py"
    dashboard_dir = CLI_ROOT / "dashboard"

    if not api_file.exists():
        console.print(f"[red]API file not found: {api_file}[/red]")
        raise typer.Exit(1)

    # Start FastAPI server
    api_port = _find_free_port()
    api_url = f"http://127.0.0.1:{api_port}"

    console.print(f"[green]Starting FastAPI server on {api_url}[/green]")

    try:
        api_proc = subprocess.Popen(
            [
                "uvicorn",
                "app.dashboard_api:app",
                "--host",
                "127.0.0.1",
                "--port",
                str(api_port),
                "--reload",
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    except FileNotFoundError:
        console.print("[red]uvicorn not found! Install: pip install uvicorn[/red]")
        raise typer.Exit(1)

    time.sleep(2)  # Wait for API to start

    # Check if dashboard exists
    if not dashboard_dir.exists():
        console.print(f"[yellow]Vue dashboard not found at: {dashboard_dir}[/yellow]")
        console.print(f"[yellow]API is running at {api_url}[/yellow]")
        console.print("[yellow]Press Ctrl+C to stop.[/yellow]")

        try:
            while True:
                time.sleep(1)
        except KeyboardInterrupt:
            console.print("\n[cyan]Stopping API...[/cyan]")
            api_proc.terminate()
        return

    # Create runtime config for Vue
    _create_env_config(dashboard_dir, api_url)

    # Start Vite dev server (changed from 'serve' to 'dev')
    console.print(f"[cyan]Starting Vite dev server in {dashboard_dir}[/cyan]")

    try:
        vue_proc = subprocess.Popen(
            ["npm", "run", "dev"],  # Changed from 'serve' to 'dev'
            cwd=str(dashboard_dir),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    except FileNotFoundError:
        console.print("[red]npm not found! Install Node.js + npm first.[/red]")
        api_proc.terminate()
        raise typer.Exit(1)

    console.print("[green]Vite dev server started.[/green]")

    # Detect Vite port (default is 5173, not 8080)
    time.sleep(3)
    vue_port = _detect_vue_port(5173)  # Vite uses 5173 by default

    if vue_port:
        console.print(
            f"\n[bold green]✓ Dashboard running at http://localhost:{vue_port}[/bold green]"
        )
        console.print(f"[dim]API: {api_url}[/dim]\n")
    else:
        console.print("[yellow]Vite started but port not detected yet...[/yellow]")
        console.print("[yellow]Try http://localhost:5173 in a few seconds.[/yellow]\n")

    console.print("Press [magenta]Ctrl+C[/magenta] to stop both servers.")

    # Keep running
    try:
        while True:
            time.sleep(0.5)

            # Check if processes are still alive
            if api_proc.poll() is not None:
                console.print("[red]API server stopped unexpectedly[/red]")
                # Print error output
                _, stderr = api_proc.communicate()
                if stderr:
                    console.print(f"[red]Error: {stderr.decode()}[/red]")
                break
            if vue_proc.poll() is not None:
                console.print("[yellow]Vue server stopped unexpectedly[/yellow]")
                # Print error output
                _, stderr = vue_proc.communicate()
                if stderr:
                    console.print(f"[yellow]Error: {stderr.decode()}[/yellow]")
                break

    except KeyboardInterrupt:
        console.print("\n[cyan]Stopping dashboard...[/cyan]")
    finally:
        # Cleanup
        if api_proc.poll() is None:
            api_proc.terminate()
            api_proc.wait(timeout=3)
        if vue_proc.poll() is None:
            vue_proc.terminate()
            vue_proc.wait(timeout=3)

        console.print("[green]Dashboard stopped.[/green]")
