import os
import time
import subprocess
import socket
from pathlib import Path
import typer
from rich.console import Console

from app.utils.pidfile import get_running_project_root

console = Console()
dashboard_app = typer.Typer(help="Run DevMemory web dashboard (FastAPI + Vue)")


def _find_free_port() -> int:
    """Find an available port"""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("", 0))
        return s.getsockname()[1]


def _create_env_config(dashboard_dir: Path, api_url: str):
    """Create env-config.js for Vue runtime configuration"""
    public_dir = dashboard_dir / "public"
    public_dir.mkdir(exist_ok=True, parents=True)

    config_content = f"""// Auto-generated by DevMemory CLI
window.DEVMEMORY_CONFIG = {{
  API_URL: "{api_url}"
}};
"""

    config_path = public_dir / "env-config.js"
    config_path.write_text(config_content)
    console.print(f"[dim]Runtime config created: {config_path}[/dim]")


def _detect_vue_port(start_port=8080, limit=10):
    """Detect Vue dev server port"""
    import http.client

    for p in range(start_port, start_port + limit):
        try:
            conn = http.client.HTTPConnection("127.0.0.1", p, timeout=0.3)
            conn.request("GET", "/")
            resp = conn.getresponse()
            html = resp.read().decode("utf-8", errors="ignore")

            if '<div id="app"' in html or "Vue" in html:
                return p
        except Exception:
            pass
    return None


@dashboard_app.command("run")
def dashboard_run():
    """Start FastAPI backend + Vue.js frontend"""

    # Check if DevMemory daemon is running
    project_root = get_running_project_root()
    if not project_root:
        console.print("[red]DevMemory daemon is not running.[/red]")
        console.print("Start it with: [bold]devmemory start[/bold]")
        raise typer.Exit(1)

    # Find directories
    CLI_ROOT = Path(__file__).resolve().parents[2]
    api_file = CLI_ROOT / "app" / "dashboard_api.py"
    dashboard_dir = CLI_ROOT / "dashboard"

    if not api_file.exists():
        console.print(f"[red]API file not found: {api_file}[/red]")
        raise typer.Exit(1)

    # Start FastAPI server
    api_port = _find_free_port()
    api_url = f"http://127.0.0.1:{api_port}"

    console.print(f"[green]Starting FastAPI server on {api_url}[/green]")

    try:
        api_proc = subprocess.Popen(
            [
                "uvicorn",
                "app.dashboard_api:app",
                "--host",
                "127.0.0.1",
                "--port",
                str(api_port),
                "--reload",
            ],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except FileNotFoundError:
        console.print("[red]uvicorn not found! Install: pip install uvicorn[/red]")
        raise typer.Exit(1)

    time.sleep(2)  # Wait for API to start

    # Check if dashboard exists
    if not dashboard_dir.exists():
        console.print(f"[yellow]Vue dashboard not found at: {dashboard_dir}[/yellow]")
        console.print(f"[yellow]API is running at {api_url}[/yellow]")
        console.print("[yellow]Press Ctrl+C to stop.[/yellow]")

        try:
            while True:
                time.sleep(1)
        except KeyboardInterrupt:
            console.print("\n[cyan]Stopping API...[/cyan]")
            api_proc.terminate()
        return

    # Create runtime config for Vue
    _create_env_config(dashboard_dir, api_url)

    # Start Vue dev server
    console.print(f"[cyan]Starting Vue dashboard in {dashboard_dir}[/cyan]")

    try:
        vue_proc = subprocess.Popen(
            ["npm", "run", "serve"],
            cwd=str(dashboard_dir),
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except FileNotFoundError:
        console.print("[red]npm not found! Install Node.js + npm first.[/red]")
        api_proc.terminate()
        raise typer.Exit(1)

    console.print("[green]Vue dashboard started.[/green]")

    # Detect Vue port
    time.sleep(3)
    vue_port = _detect_vue_port()

    if vue_port:
        console.print(
            f"\n[bold green]✓ Dashboard running at http://localhost:{vue_port}[/bold green]"
        )
        console.print(f"[dim]API: {api_url}[/dim]\n")
    else:
        console.print("[yellow]Vue started but port not detected yet...[/yellow]")
        console.print("[yellow]Try http://localhost:8080 in a few seconds.[/yellow]\n")

    console.print("Press [magenta]Ctrl+C[/magenta] to stop both servers.")

    # Keep running
    try:
        while True:
            time.sleep(0.5)

            # Check if processes are still alive
            if api_proc.poll() is not None:
                console.print("[red]API server stopped unexpectedly[/red]")
                break
            if vue_proc.poll() is not None:
                console.print("[yellow]Vue server stopped[/yellow]")
                break

    except KeyboardInterrupt:
        console.print("\n[cyan]Stopping dashboard...[/cyan]")
    finally:
        # Cleanup
        if api_proc.poll() is None:
            api_proc.terminate()
        if vue_proc.poll() is None:
            vue_proc.terminate()

        console.print("[green]Dashboard stopped.[/green]")
